"""Explicit, reviewed coverage; never discover profile members by a filename glob."""
PROFILES = {
    "chaos-quick": (
        "bounded-eos", "commit-request-lost", "commit-response-lost",
        "broker-leader-kill-v1", "broker-leader-pause-v1", "broker-coordinator-pause-v1",
        "coordinator-commit-kill-v2", "protocol-endtxn-delay-v2",
        "protocol-endtxn-coordinator-v2", "protocol-produce-response-v2",
    ),
    "chaos-full": (
        "bounded-eos", "commit-request-lost", "commit-response-lost",
        "broker-eos-control-v1", "broker-eos-control-v2",
        "broker-eos-kill-v1", "broker-eos-kill-v2",
        "broker-leader-kill-v1", "broker-leader-kill-v2",
        "broker-leader-pause-v1", "broker-leader-pause-v2",
        "broker-coordinator-pause-v1", "broker-coordinator-pause-v2",
        "protocol-endtxn-request-v1", "protocol-endtxn-request-v2",
        "protocol-endtxn-delay-v1", "protocol-endtxn-delay-v2",
        "protocol-endtxn-coordinator-v1", "protocol-endtxn-coordinator-v2",
        "protocol-produce-response-v1", "protocol-produce-response-v2",
        "protocol-add-partitions-concurrent-v1",
        "protocol-produce-after-append-v1", "protocol-produce-after-append-v2",
        "coordinator-commit-kill-v1", "coordinator-commit-kill-v2",
        "coordinator-commit-pause-v1", "coordinator-commit-pause-v2",
        "pooling-bounded-eos-v1",
        "pooling-commit-request-lost-v1",
        "pooling-commit-response-lost-v1",
        "pooling-coordinator-commit-kill-v1",
        "pooling-broker-control-v1",
        "pooling-describe-producers-delay-v1",
        "pooling-describe-producers-delay-broker-down-v1",
        "pooling-describe-producers-error-response-v1",
        "pooling-describe-producers-error-response-broker-down-v1",
        "pooling-describe-producers-drop-response-v1",
        "pooling-describe-producers-drop-response-broker-down-v1",
        "pooling-list-transactions-delay-v1",
        "pooling-list-transactions-delay-broker-down-v1",
        "pooling-list-transactions-error-response-v1",
        "pooling-list-transactions-error-response-broker-down-v1",
        "pooling-list-transactions-drop-response-v1",
        "pooling-list-transactions-drop-response-broker-down-v1",
        "pooling-bounded-eos-v2",
        "pooling-commit-request-lost-v2",
        "pooling-commit-response-lost-v2",
        "pooling-coordinator-commit-kill-v2",
        "pooling-broker-control-v2",
        "pooling-describe-producers-delay-v2",
        "pooling-describe-producers-delay-broker-down-v2",
        "pooling-describe-producers-error-response-v2",
        "pooling-describe-producers-error-response-broker-down-v2",
        "pooling-describe-producers-drop-response-v2",
        "pooling-describe-producers-drop-response-broker-down-v2",
        "pooling-list-transactions-delay-v2",
        "pooling-list-transactions-delay-broker-down-v2",
        "pooling-list-transactions-error-response-v2",
        "pooling-list-transactions-error-response-broker-down-v2",
        "pooling-list-transactions-drop-response-v2",
        "pooling-list-transactions-drop-response-broker-down-v2",
    ),
}
